export const PATHS = {
	HOME: "/",
	LOGIN: "/login",
	DASHBOARD: "/dashboard",
	ADMIN_PANEL: "/admin-panel",
	REGISTER: "/register",
	CART: "/cart",
	NEW_ARRIVALS: "/new-arrivals",
	BEST_SELLERS: "/best-sellers",
	SHOP_ALL: "/shop-all",
	UNISEX: "/unisex",
	COLORS: "/colors",
	WISHLIST: "/wishlist",
	FAQ: "/faq",
	RETURN_POLICY: "/return-policy",
	REFUND_POLICY: "/refund-policy",
	TERMS_AND_CONDITIONS: "/terms-and-conditions",
	CONTACT_US: "/contact-us",
	PRIVACY_POLICY: "/privacy-policy",	
} as const;

